
INSERT INTO `director` (`pk_id_director`, `foto_director`, `nombre_director`, `oscar_director`, `sexo`, `edad_director`, `director_fallecido`, `nacionalidad_director`) VALUES
(1, '', 'Nancy Meyers', 'N', 'Mujer', 75, NULL, 'USA'),
(2, '', 'James Mangold', 'N', 'Hombre', 59, NULL, 'USA'),
(3, '', 'Joseph Kosinski', 'N', 'Hombre', 49, NULL, 'USA'),
(4, '', 'Jonathan Goldstein', 'N', 'Hombre', 58, NULL, 'USA'),
(5, '', 'Aaron Sorkin', 'S', 'Hombre', 61, NULL, 'USA'),
(6, '', 'Robert Rodriguez', 'N', 'Hombre', 54, NULL, 'USA'),
(7, '', 'Santiago Segura', 'N', 'Hombre', 56, NULL, 'España'),
(8, '', 'Ridley Scott', 'S', 'Hombre', 85, NULL, 'UK'),
(9, '', 'Steven Spielberg', 'S', 'Hombre', 76, NULL, 'USA'),
(10, '', 'Joss Whedon', 'N', 'Hombre', 58, NULL, 'USA'),
(11, '', 'Fred Zinnemann', 'S', 'Hombre', 89, NULL, 'USA'),
(12, 'vacio', 'Paul Urkijo Alijo', 'N', 'Hombre', 38, NULL, 'España'),
(13, 'vacio', 'Cary Fukunaga', 'N', 'Hombre', 45, NULL, 'USA'),
(14, 'vacio', 'Sam Mendes', 'S', 'Hombre', 57, NULL, 'UK'),
(15, 'vacio', 'Martin Campbell', 'N', 'Hombre', 79, NULL, 'Nueva Zelanda'),
(16, 'vacio', 'Neill Blomkamp', 'N', 'Hombre', 43, NULL, 'Canadá'),
(17, 'vacio', 'Peter Jackson', 'S', 'Hombre', 61, NULL, 'Nueva Zelanda'),
(18, 'vacio', 'David Lean', 'S', 'Hombre', 83, 'S', 'UK'),
(19, 'vacio', 'Tony Scott', 'N', 'Hombre', 68, NULL, 'USA'),
(20, 'vacio', 'F. Gary Gray', 'N', 'Hombre', 52, NULL, 'USA'),
(21, 'vacio', 'Christopher Nolan', 'N', 'Hombre', 52, NULL, 'UK'),
(22, 'vacio', 'John Ford', 'S', 'Hombre', 79, 'S', 'USA'),
(23, 'vacio', 'Matt Reeves', 'N', 'Hombre', 57, NULL, 'USA'),
(24, '', 'James Cameron', 'S', 'Hombre', 68, NULL, 'Canadá'),
(25, 'vacio', 'Sam Raimi', 'N', 'Hombre', 63, NULL, 'USA'),
(26, 'vacio', 'Neil Marshall', 'N', 'Hombre', 53, NULL, 'UK'),
(27, 'vacio', 'John McTiernan', 'N', 'Hombre', 72, NULL, 'USA'),
(28, 'vacio', 'Mark Robson', 'N', 'Hombre', 64, 'S', 'Canadá'),
(29, 'vacio', 'Peter Weir', 'N', 'Hombre', 78, NULL, 'Australia'),
(30, 'vacio', 'Gus Van Sant', 'N', 'Hombre', 70, NULL, 'USA'),
(31, 'vacio', 'Ron Howard', 'S', 'Hombre', 69, NULL, 'USA'),
(32, 'vacio', 'George Lucas', 'N', 'Hombre', 79, NULL, 'USA'),
(33, 'vacio', 'John Milius', 'N', 'Hombre', 79, NULL, 'USA'),
(34, 'vacio', 'David Yates', 'N', 'Hombre', 59, NULL, 'UK'),
(35, 'vacio', 'Richard Donner', 'N', 'Hombre', 91, 'S', 'USA'),
(36, 'vacio', 'Sylvester Stallone', 'N', 'Hombre', 76, NULL, 'USA'),
(37, 'vacio', 'Gore Verbinski', 'S', 'Hombre', 59, NULL, 'USA'),
(38, 'vacio', 'Kevin Costner', 'S', 'Hombre', 68, NULL, 'USA'),
(39, 'vacio', 'Don Coscarelli', 'N', 'Hombre', 69, NULL, 'USA'),
(40, 'vacio', 'Antoine Fuqua', 'N', 'Hombre', 58, NULL, 'USA'),
(41, 'vacio', 'Guillermo del Toro', 'S', 'Hombre', 58, NULL, 'México'),
(42, 'vacio', 'Kenneth Branagh', 'S', 'Hombre', 63, NULL, 'UK'),
(43, 'vacio', 'Guy Ritchie', 'N', 'Hombre', 59, NULL, 'UK'),
(44, 'vacio', 'Russell Mulcahy', 'N', 'Hombre', 70, NULL, 'Australia'),
(45, 'vacio', 'Stephen Hopkins', 'N', 'Hombre', 65, NULL, 'Jamaica'),
(46, 'vacio', 'Kevin Reynolds', 'N', 'Hombre', 71, NULL, 'USA'),
(47, 'vacio', 'Denis Villeneuve', 'N', 'Hombre', 56, NULL, 'Canadá'),
(48, '', 'Stephen Sommers', 'N', 'Hombre', 61, NULL, 'USA'),
(49, 'vacio', 'Irvin Kershner', 'N', 'Hombre', 87, 'S', 'USA'),
(50, 'vacio', 'Richard Marquand', 'N', 'Hombre', 49, 'S', 'UK'),
(51, 'vacio', 'Luc Besson', 'N', 'Hombre', 64, NULL, 'Francia'),
(52, 'vacio', 'Chuck Russell', 'N', 'Hombre', 65, NULL, 'USA'),
(53, 'vacio', 'Sam Weisman', 'N', 'Hombre', 75, NULL, 'USA'),
(54, 'vacio', 'Clint Eastwood', 'S', 'Hombre', 93, NULL, 'USA'),
(55, 'vacio', 'Zack Snyder', 'N', 'Hombre', 57, NULL, 'USA'),
(56, 'vacio', 'Noam Murro', 'N', 'Hombre', 62, NULL, 'Israel'),
(57, 'vacio', 'Robert Zemeckis', 'S', 'Hombre', 71, NULL, 'USA'),
(58, 'vacio', 'John Carpenter', 'N', 'Hombre', 75, NULL, 'USA'),
(59, 'vacio', 'Patty Jenkins', 'N', 'Mujer', 51, NULL, 'USA'),
(60, 'vacio', 'Ralph Nelson', 'N', 'Hombre', 71, 'S', 'USA'),
(61, 'vacio', 'James Wan', 'N', 'Hombre', 46, NULL, 'Malasia'),
(62, 'vacio', 'Andy Muschietti', 'N', 'Hombre', 49, NULL, 'Argentina'),
(63, 'vacio', 'Joe Johnston', 'S', 'Hombre', 73, NULL, 'USA'),
(64, 'vacio', 'Anthony Russo', 'N', 'Hombre', 53, NULL, 'USA'),
(65, 'vacio', 'Joe Russo', 'N', 'Hombre', 52, NULL, 'USA'),
(66, 'vacio', 'Jon Favreau', 'N', 'Hombre', 57, NULL, 'USA'),
(67, 'vacio', 'Matthew Vaughn', 'N', 'Hombre', 52, NULL, 'UK'),
(68, 'vacio', 'Sergey Bodrov', 'N', 'Hombre', 75, 'S', 'Rusia'),
(69, 'vacio', 'Roar Uthaug', 'N', 'Hombre', 50, NULL, 'Noruega'),
(70, 'vacio', 'Christian Rivers', 'S', 'Hombre', 49, NULL, 'Nueva Zelanda'),
(71, 'vacio', 'Jordan Vogt-Roberts', 'N', 'Hombre', 39, NULL, 'USA'),
(72, 'vacio', 'Anna Boden', 'N', 'Mujer', 44, NULL, 'USA'),
(73, 'vacio', 'Rob Reiner', 'N', 'Hombre', 76, NULL, 'USA'),
(74, 'vacio', 'Simon Wincer', 'N', 'Hombre', 80, NULL, 'Australia'),
(75, 'vacio', 'Andrew Stanton', 'S', 'Hombre', 58, NULL, 'USA'),
(76, 'vacio', 'Duncan Jones', 'N', 'Hombre', 52, NULL, 'UK'),
(77, 'vacio', 'Gavin Hood', 'S', 'Hombre', 60, NULL, 'Sudáfrica'),
(78, 'vacio', 'Peter Berg', 'N', 'Hombre', 59, NULL, 'USA'),
(79, 'vacio', 'Martin Scorsese', 'S', 'Hombre', 80, NULL, 'Italia'),
(80, 'vacio', 'Roland Emmerich', 'N', 'Hombre', 67, NULL, 'Alemania'),
(81, 'vacio', 'John Sturges', 'N', 'Hombre', 82, 'S', 'USA'),
(82, 'vacio', 'Mike Hodges', 'N', 'Hombre', 90, 'S', 'UK'),
(83, 'vacio', 'Michael Anderson', 'S', 'Hombre', 98, 'S', 'UK'),
(84, 'vacio', 'Simon Wells', 'N', 'Hombre', 62, NULL, 'USA'),
(85, 'vacio', 'George Pal', 'S', 'Hombre', 72, 'S', 'USA'),
(86, 'vacio', 'William Wyler', 'S', 'Hombre', 79, 'S', 'USA'),
(87, 'vacio', 'Taika Waititi', 'S', 'Hombre', 47, NULL, 'Nueva Zelanda'),
(88, 'vacio', 'John Hughes', 'N', 'Hombre', 59, 'S', 'USA'),
(89, 'vacio', 'Richard Fleischer', 'S', 'Hombre', 89, 'S', 'USA'),
(90, 'vacio', 'Fred M. Wilcox', 'N', 'Hombre', 56, 'S', 'USA'),
(91, 'vacio', 'Marcus Nispel', 'N', 'Hombre', 60, NULL, 'Alemania'),
(92, 'vacio', 'Lawrence Kasdan', 'N', 'Hombre', 74, NULL, 'USA'),
(93, 'vacio', 'Sergio Leone', 'N', 'Hombre', 60, 'S', 'Italia'),
(94, 'vacio', 'Delmer Daves', 'N', 'Hombre', 73, 'S', 'USA'),
(95, 'vacio', 'David F. Sandberg', 'N', 'Hombre', 42, NULL, 'Suecia'),
(96, 'vacio', 'Jaume Collet-Serra', 'N', 'Hombre', 49, NULL, 'España'),
(97, 'vacio', 'J.J. Abrams', 'N', 'Hombre', 57, NULL, 'USA'),
(98, 'vacio', 'Justin Lin', 'N', 'Hombre', 50, NULL, 'Taiwán'),
(99, 'vacio', 'Alex Kurtzman', 'N', 'Hombre', 50, NULL, 'USA'),
(100, 'vacio', 'Michael Bay', 'N', 'Hombre', 58, NULL, 'USA'),
(101, 'vacio', 'Peyton Reed', 'N', 'Hombre', 59, NULL, 'USA'),
(102, 'vacio', 'Mike Newell', 'N', 'Hombre', 81, NULL, 'UK'),
(103, 'vacio', 'Howard Deutch', 'N', 'Hombre', 72, NULL, 'USA'),
(104, 'vacio', 'Roger Michell', 'N', 'Hombre', 65, NULL, 'UK'),
(105, 'vacio', 'Iain Softley', 'N', 'Hombre', 66, NULL, 'UK'),
(106, 'vacio', 'Marc Lawrence', 'N', 'Hombre', 63, NULL, 'USA'),
(107, 'vacio', 'Scott Derrickson', 'N', 'Hombre', 57, NULL, 'USA'),
(108, 'vacio', 'Desmond Davis', 'N', 'Hombre', 97, NULL, 'UK'),
(109, 'vacio', 'Louis Leterrier', 'N', 'Hombre', 50, NULL, 'Francia'),
(110, 'vacio', 'Jonathan Liebesman', 'N', 'Hombre', 47, NULL, 'Sudáfrica'),
(111, 'vacio', 'Tarsem Singh', 'N', 'Hombre', 62, NULL, 'India'),
(112, 'vacio', 'Renny Harlin', 'N', 'Hombre', 64, NULL, 'Finlandia'),
(113, 'vacio', 'Neil Burger', 'N', 'Hombre', 60, NULL, 'USA'),
(114, 'vacio', 'Nicolas Winding Refn', 'N', 'Hombre', 52, NULL, 'Dinamarca'),
(115, 'vacio', 'Tomasz Bagiński', 'N', 'Hombre', 47, NULL, 'Polonia'),
(116, 'vacio', 'Victor Fleming', 'S', 'Hombre', 59, 'S', 'USA'),
(117, 'vacio', 'Ben Stiller', 'N', 'Hombre', 58, NULL, 'USA'),
(118, 'vacio', 'Don Chaffey', 'N', 'Hombre', 73, 'S', 'UK'),
(119, 'vacio', 'Dean DeBlois', 'N', 'Hombre', 53, NULL, 'Canadá'),
(120, 'vacio', 'Gareth Edwards', 'N', 'Hombre', 48, NULL, 'UK'),
(121, 'vacio', 'Matthew Robbins', 'N', 'Hombre', 78, NULL, 'USA'),
(122, 'vacio', 'Greta Gerwig', 'N', 'Mujer', 39, NULL, 'USA'),
(123, 'vacio', 'Michael Mann', 'N', 'Hombre', 80, NULL, 'USA'),
(124, 'vacio', 'Rob Bowman', 'N', 'Hombre', 63, NULL, 'USA'),
(125, 'vacio', 'Enrique Gato', 'N', 'Hombre', 46, NULL, 'España'),
(126, 'vacio', 'Rian Johnson', 'N', 'Hombre', 49, NULL, 'USA'),
(127, 'vacio', 'John Musker', 'N', 'Hombre', 69, NULL, 'USA'),
(128, 'vacio', 'Herbert Ross', 'N', 'Hombre', 74, NULL, 'USA'),
(129, 'vacio', 'Craig Brewer', 'N', 'Hombre', 52, NULL, 'USA'),
(130, 'vacio', 'Brett Ratner', 'N', 'Hombre', 54, NULL, 'USA'),
(131, 'vacio', 'Richard Curtis', 'N', 'Hombre', 67, NULL, 'Nueva Zelanda'),
(132, 'vacio', 'Alfred Hitchcock', 'S', 'Hombre', 80, 'S', 'UK'),
(133, 'vacio', 'Paul Schneider', 'N', 'Hombre', 1, NULL, 'Desconocido'),
(134, 'vacio', 'Paul King', 'N', 'Hombre', 45, NULL, 'UK'),
(135, 'vacio', 'Will Gluck', 'N', 'Hombre', 45, NULL, 'USA');
