
INSERT INTO `genero` (`pk_id_genero`, `nombre_genero`, `descripcion`) VALUES
(1, 'Aventuras', ''),
(2, 'Acción', ''),
(3, 'Comedia', ''),
(4, 'Fantasía', ''),
(5, 'Drama', ''),
(6, 'Ciencia-ficción', ''),
(7, 'Terror', ''),
(8, 'Bélico', ''),
(9, 'Western', ''),
(10, 'Superheróico', 'Para todas las películas de superhéroes'),
(11, 'Suspense', ''),
(12, 'Monstruos', ''),
(13, 'Héroes clásicos', 'Películas con encanto'),
(14, 'Comedia juvenil', 'Película de culto'),
(15, 'Mitología', ''),
(16, 'Animación', ''),
(17, 'Thriller', ''),
(18, 'Animación', '');
