
INSERT INTO `produccion` (`pk_id_produccion`, `nombre_produccion`) VALUES
(7, '20th Century Fox'),
(6, 'ADS Service'),
(4, 'Amazon Studios'),
(29, 'Atmosphere Entertainment MM'),
(10, 'Bainet Taldea'),
(5, 'Columbia Pictures'),
(27, 'Constantin Film'),
(34, 'Coproducción Reino Unido-Estados Unidos'),
(24, 'Dino de Laurentiis'),
(18, 'Dovemead Films'),
(35, 'DreamWorks Animation'),
(31, 'FilmDistrict'),
(38, 'Konigsberg/Sanitsky Company'),
(22, 'Legendary Pictures'),
(25, 'Lionsgate'),
(37, 'Lucasfilm'),
(8, 'Marvel Studios'),
(11, 'Metro-Goldwyn-Mayer'),
(32, 'Michael London Productions'),
(17, 'Miramax'),
(13, 'New Line Cinema'),
(20, 'Orion Pictures'),
(3, 'Paramount Pictures'),
(28, 'Polygram Filmed Entertainment'),
(26, 'Produzioni Europee Associati'),
(30, 'Relativity Studios'),
(14, 'Republic Pictures'),
(16, 'Roxbury Productions'),
(33, 'Sony Pictures'),
(23, 'Summit Entertainment'),
(36, 'Telecinco Cinema'),
(21, 'Thorn EMI Screen Entertainment'),
(15, 'Touchstone Pictures'),
(12, 'TriStar Pictures'),
(19, 'United Artists'),
(9, 'Universal Pictures'),
(2, 'Walt Disney'),
(1, 'Warner Bros.');
